[package]
name = "solana-counter-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = { version = "1.5.7", features = ["derive"] }
solana-program = "3.0.0"

